#include "mapping.h"

namespace sdds {
    Route Route::getBlueRoute() const
    {
        Route blue_route;
        blue_route.addPoint(Point(0, 0))
            .addPoint(Point(1, 0))
            .addPoint(Point(2, 0))
            .addPoint(Point(3, 0))
            .addPoint(Point(4, 0))
            .addPoint(Point(4, 1))
            .addPoint(Point(4, 2))
            .addPoint(Point(4, 3))
            .addPoint(Point(4, 4))
            .addPoint(Point(4, 5))
            .addPoint(Point(4, 6))
            .addPoint(Point(4, 7))
            .addPoint(Point(4, 8))
            .addPoint(Point(4, 9))
            .addPoint(Point(5, 9))
            .addPoint(Point(6, 9))
            .addPoint(Point(7, 9))
            .addPoint(Point(8, 9))
            .addPoint(Point(9, 9))
            .addPoint(Point(10, 9))
            .addPoint(Point(10, 10))
            .addPoint(Point(11, 10))
            .addPoint(Point(12, 10))
            .addPoint(Point(13, 10))
            .addPoint(Point(14, 10))
            .addPoint(Point(15, 10))
            .addPoint(Point(16, 10))
            .addPoint(Point(17, 10))
            .addPoint(Point(17, 11))
            .addPoint(Point(17, 12))
            .addPoint(Point(17, 13))
            .addPoint(Point(17, 14))
            .addPoint(Point(17, 15))
            .addPoint(Point(17, 16))
            .addPoint(Point(17, 17))
            .addPoint(Point(17, 18))
            .addPoint(Point(17, 19))
            .addPoint(Point(17, 20))
            .addPoint(Point(17, 21))
            .addPoint(Point(17, 22))
            .addPoint(Point(17, 23))
            .addPoint(Point(17, 24));

        return blue_route;
    }

    Route Route::getGreenRoute() const
    {
        Route green_route;
        green_route.addPoint(Point(0, 0))
            .addPoint(Point(1, 0))
            .addPoint(Point(2, 0))
            .addPoint(Point(3, 0))
            .addPoint(Point(4, 0))
            .addPoint(Point(4, 1))
            .addPoint(Point(4, 2))
            .addPoint(Point(4, 3))
            .addPoint(Point(4, 4))
            .addPoint(Point(4, 5))
            .addPoint(Point(4, 6))
            .addPoint(Point(4, 7))
            .addPoint(Point(4, 8))
            .addPoint(Point(4, 9))
            .addPoint(Point(4, 10))
            .addPoint(Point(4, 11))
            .addPoint(Point(3, 11))
            .addPoint(Point(2, 11))
            .addPoint(Point(1, 11))
            .addPoint(Point(0, 11))
            .addPoint(Point(0, 12))
            .addPoint(Point(0, 13))
            .addPoint(Point(0, 14))
            .addPoint(Point(0, 15))
            .addPoint(Point(0, 16))
            .addPoint(Point(0, 17))
            .addPoint(Point(0, 18))
            .addPoint(Point(0, 19))
            .addPoint(Point(1, 19))
            .addPoint(Point(2, 19))
            .addPoint(Point(3, 19))
            .addPoint(Point(4, 19))
            .addPoint(Point(5, 19))
            .addPoint(Point(6, 19))
            .addPoint(Point(7, 19))
            .addPoint(Point(8, 19))
            .addPoint(Point(9, 19))
            .addPoint(Point(9, 20))
            .addPoint(Point(9, 21))
            .addPoint(Point(9, 22))
            .addPoint(Point(9, 23))
            .addPoint(Point(9, 24));

        return green_route;
    }

    Route Route::getYellowRoute() const
    {
        Route yellow_route;
        yellow_route.addPoint(Point(0, 0))
            .addPoint(Point(1, 0))
            .addPoint(Point(2, 0))
            .addPoint(Point(3, 0))
            .addPoint(Point(4, 0))
            .addPoint(Point(4, 1))
            .addPoint(Point(4, 2))
            .addPoint(Point(4, 3))
            .addPoint(Point(5, 3))
            .addPoint(Point(6, 3))
            .addPoint(Point(7, 3))
            .addPoint(Point(8, 3))
            .addPoint(Point(9, 3))
            .addPoint(Point(9, 2))
            .addPoint(Point(9, 1))
            .addPoint(Point(10, 1))
            .addPoint(Point(11, 1))
            .addPoint(Point(12, 1))
            .addPoint(Point(13, 1))
            .addPoint(Point(14, 1))
            .addPoint(Point(15, 1))
            .addPoint(Point(16, 1))
            .addPoint(Point(17, 1))
            .addPoint(Point(18, 1))
            .addPoint(Point(19, 1))
            .addPoint(Point(19, 2))
            .addPoint(Point(19, 3))
            .addPoint(Point(19, 4))
            .addPoint(Point(19, 5))
            .addPoint(Point(19, 6))
            .addPoint(Point(19, 7))
            .addPoint(Point(19, 8))
            .addPoint(Point(19, 9))
            .addPoint(Point(19, 10))
            .addPoint(Point(19, 11))
            .addPoint(Point(19, 12))
            .addPoint(Point(19, 13))
            .addPoint(Point(19, 14))
            .addPoint(Point(19, 15))
            .addPoint(Point(19, 16))
            .addPoint(Point(19, 17))
            .addPoint(Point(19, 18))
            .addPoint(Point(19, 19))
            .addPoint(Point(19, 20))
            .addPoint(Point(19, 21))
            .addPoint(Point(19, 22))
            .addPoint(Point(19, 23))
            .addPoint(Point(19, 24));

        return yellow_route;
    }
}  // namespace sdds
